apiVersion: apps/v1beta1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: cloudwatch-logs-adapter-v1
spec:
  selector: 
    matchLabels:
      app: cloudwatch-logs-adapter-v1
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudwatch-logs-adapter-v1
    spec:
      containers:
      - name: cloudwatch-logs-adapter-v1
        image: consortit-docker-cme-local.jfrog.io/cloudwatch-logs-adapter:image-version
        ports:
        - containerPort: 8080
        - containerPort: 8081
        env:
        - name: queueaccesskey
          valueFrom:
            secretKeyRef:
              name: cloudwatch-logs-secret
              key: queueaccesskey
        - name: queuesecretkey
          valueFrom:
            secretKeyRef:
              name: cloudwatch-logs-secret
              key: queuesecretkey
        - name: jwk_url
          value: "https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_M4FyC0JPA/.well-known/jwks.json"
        - name: jwk_kid
          value: "ImJm862bLPCtlhQQy368BAoKPayD9DLpNwywW2fhZPI="
        - name: jwk_alg
          value: "RS256"
      imagePullSecrets:
        - name: regsecret
---
apiVersion: v1
kind: Service
metadata:
  name: cloudwatch-logs-adapter-v1
  labels:
    app: cloudwatch-logs-adapter-v1
    version: v1
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: external
    - port: 81
      protocol: TCP
      targetPort: 8081
      name: external2
  selector:
    app: cloudwatch-logs-adapter-v1
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cloudwatch-logs-adapter-v1
  labels:
    app: cloudwatch-logs-adapter-v1
spec:
  rules:
  - host: "cme.dev.k8s.consort-it.de"
    http:
      paths:
      - path: /api/v1/cloudwatch-logs-adapter
        backend:
          serviceName: cloudwatch-logs-adapter-v1
          servicePort: 80
      - path: /api/v1/cloudwatch-logs-adapter/health
        backend:
          serviceName: cloudwatch-logs-adapter-v1
          servicePort: 81
      - path: /api/v1/cloudwatch-logs-adapter/metrics
        backend:
          serviceName: cloudwatch-logs-adapter-v1
          servicePort: 81
